AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'spec/spec_helper.rb'
    - 'bin/*'
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 14
Naming/MethodParameterName:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/RedundantInterpolation:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/Not:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/LineLength:
  Max: 110
  IgnoredPatterns: ['^(\s+)?#']
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
